name: '@delivery-much/actions-chat'
description: 'Send Google Chat notifications'
branding:
  icon: 'pen-tool'  
  color: 'black'
inputs:
  url:
    description: 'Google Chat Webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'